[package]
name = "opentracing"
description = "opentracing"
version = "0.1.0"
license = "MIT"
authors = ["ccc13 <currantxx@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1.13"
futures = "0.1.25"
