[package]
name = "opentracing-jaeger"
description = "jaeger for opentracing"
version = "0.1.0"
license = "MIT"
authors = ["ccc13 <currantxx@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"

opentracing = { path = "../opentracing" }
